### ISSUE TITLE
Add an readme to setup the project and some description about the project

### ISSUE THREAD

**Issue by sanjevShakya** [b7Rexx/dota-card-game-api#2]

**Comment by b7Rexx** [comment]
update on DCG-0004

**Comment by koiralakiran1** [comment]
> update on DCG-0004

You can setup **Projects** so that the transition of issues after changes to pull requests are automated. 
![image](https://user-images.githubusercontent.com/11130898/77879671-a0593980-727a-11ea-9e11-7e7578cfff49.png)
